### ISSUE TITLE
Syncing Sonarr Issue

### ISSUE THREAD

**Issue by solskyer** [Archmonger/Conreq#286]
### Describe the bug

First of all Conreq is a great solution!!!
I installed conreq on my synology using docker. im having problem with sonarr configuration (always loading). 
with radarr its all ok! I can add movie

I found this in the logs file
2024-06-26 12:50:47,235 ERROR conreq.core.arrs.sonarr: Failed to get sonarr root dirs!
Traceback (most recent call last):
  File "/app/conreq/conreq/core/arrs/sonarr.py", line 309, in sonarr_root_dirs
    return self.__sonarr.get_root_folder()
  File "/usr/lib/python3.10/site-packages/pyarr/base.py", line 93, in get_root_folder
    return self.request_get(path, self.ver_uri)
  File "/usr/lib/python3.10/site-packages/pyarr/request_handler.py", line 81, in request_get
    return _process_response(res)
  File "/usr/lib/python3.10/site-packages/pyarr/request_handler.py", line 186, in _process_response
    raise PyarrResourceNotFound("Resource not found")
pyarr.exceptions.PyarrResourceNotFound: Resource not found

### Conreq Version

0.20.51

### Conreq Branch

Main (Default)

### Server Operating System

Other

### Client Operating System

Other

### Client Browser(s)

Safari

### Log Info

```shell
2024-06-26 12:50:47,235 ERROR conreq.core.arrs.sonarr: Failed to get sonarr root dirs!
Traceback (most recent call last):
  File "/app/conreq/conreq/core/arrs/sonarr.py", line 309, in sonarr_root_dirs
    return self.__sonarr.get_root_folder()
  File "/usr/lib/python3.10/site-packages/pyarr/base.py", line 93, in get_root_folder
    return self.request_get(path, self.ver_uri)
  File "/usr/lib/python3.10/site-packages/pyarr/request_handler.py", line 81, in request_get
    return _process_response(res)
  File "/usr/lib/python3.10/site-packages/pyarr/request_handler.py", line 186, in _process_response
    raise PyarrResourceNotFound("Resource not found")
pyarr.exceptions.PyarrResourceNotFound: Resource not found
```

**Comment by Archmonger** [comment]
Thanks for the issue!

I am working on a fix. Apologies for the delays!

**Comment by Archmonger** [comment]
Fixed.

If you are using Docker, you will need to change your image URL.

[See the docs for details](https://archmonger.github.io/Conreq/latest/install/docker/).
