### ISSUE TITLE
'bool' object is not subscriptable

### ISSUE THREAD

**Issue by APantslessMan** [Archmonger/Conreq#3]
Upon initiating request, get failed error message. 

```python
2021-02-06 00:23:30,426 ERROR django.request: Internal Server Error: /request/
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/asgiref/sync.py", line 339, in thread_handler
    raise exc_info[1]
  File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.8/site-packages/asgiref/sync.py", line 304, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/asgiref/sync.py", line 343, in thread_handler
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./conreq/apps/user_requests/views.py", line 104, in request_content
    radarr_params = obtain_radarr_parameters(
  File "./conreq/utils/apps.py", line 432, in obtain_radarr_parameters
    radarr_root = is_key_value_in_list(
TypeError: 'bool' object is not subscriptable
```

**Comment by Archmonger** [comment]
Are you using `BASE_URL`?

**Comment by APantslessMan** [comment]
Not using base_url, and format for son/rad is http://10.10.13.231:7878 for example. API connects, the quality and directory drop downs populate. 

Clean install on unraid docker

**Comment by Archmonger** [comment]
What version of Radarr are you running?

**Comment by APantslessMan** [comment]
Radar is 3.0.0.3970 sonarr is 3.0.4.1091
I noticed a cannot set directories even though they are populated. Log shows a web socket error. 

also found this in the docker log whenever trying a request. 
`Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/asgiref/sync.py", line 339, in thread_handler
raise exc_info[1]
File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
response = await get_response(request)
File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
response = await wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python3.8/site-packages/asgiref/sync.py", line 304, in __call__
ret = await asyncio.wait_for(future, timeout=None)
File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
return await fut
File "/usr/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 23, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.8/site-packages/asgiref/sync.py", line 343, in thread_handler
return func(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
response = view_func(request, *args, **kwargs)
File "/usr/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "./conreq/apps/more_info/views.py", line 171, in series_modal
sonarr_params = obtain_sonarr_parameters(
File "./conreq/utils/apps.py", line 401, in obtain_sonarr_parameters
sonarr_root = is_key_value_in_list(
TypeError: 'bool' object is not subscriptable
ERROR django.request: Internal Server Error: /more_info/series_modal/`

**Comment by Archmonger** [comment]
thanks for that log, exactly what I needed.

**Comment by Archmonger** [comment]
Update your docker two hours from now, should be fixed 👍
